// <auto-generated />
using System;
using Libreria.Infraestructura.AccesoDatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libreria.Infraestructura.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    partial class LibreriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdObjeto")
                        .HasColumnType("int");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("MetodosPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Credito"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Efectivo"
                        });
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoGastoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("TipoGastoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pagos");

                    b.HasDiscriminator<string>("TipoPago").HasValue("Pago");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.TipoGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TiposGasto");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Rol");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Rol").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.PagoRecurrente", b =>
                {
                    b.HasBaseType("Libreria.LogicaNegocio.Entidades.Pago");

                    b.HasDiscriminator().HasValue("Recurrente");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.PagoUnico", b =>
                {
                    b.HasBaseType("Libreria.LogicaNegocio.Entidades.Pago");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaPago");

                    b.Property<string>("NumeroRecibo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NumeroRecibo");

                    b.HasDiscriminator().HasValue("Unico");
                });

            modelBuilder.Entity("Admin", b =>
                {
                    b.HasBaseType("Usuario");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Empleado", b =>
                {
                    b.HasBaseType("Usuario");

                    b.HasDiscriminator().HasValue("Empleado");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Gerente", b =>
                {
                    b.HasBaseType("Usuario");

                    b.HasDiscriminator().HasValue("Gerente");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoNombreEquipo", "Nombre", b1 =>
                        {
                            b1.Property<int>("EquipoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nombre");

                            b1.HasKey("EquipoId");

                            b1.ToTable("Equipos");

                            b1.WithOwner()
                                .HasForeignKey("EquipoId");
                        });

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.HasOne("Libreria.LogicaNegocio.Entidades.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Libreria.LogicaNegocio.Entidades.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("TipoGastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoDescripcionGasto", "Descripcion", b1 =>
                        {
                            b1.Property<int>("PagoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Descripcion");

                            b1.HasKey("PagoId");

                            b1.ToTable("Pagos");

                            b1.WithOwner()
                                .HasForeignKey("PagoId");
                        });

                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoMonto", "Monto", b1 =>
                        {
                            b1.Property<int>("PagoId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Monto");

                            b1.HasKey("PagoId");

                            b1.ToTable("Pagos");

                            b1.WithOwner()
                                .HasForeignKey("PagoId");
                        });

                    b.Navigation("Descripcion")
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Monto")
                        .IsRequired();

                    b.Navigation("TipoGasto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.TipoGasto", b =>
                {
                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoDescripcionGasto", "Descripcion", b1 =>
                        {
                            b1.Property<int>("TipoGastoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Descripcion");

                            b1.HasKey("TipoGastoId");

                            b1.ToTable("TiposGasto");

                            b1.WithOwner()
                                .HasForeignKey("TipoGastoId");
                        });

                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoNombreGasto", "Nombre", b1 =>
                        {
                            b1.Property<int>("TipoGastoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nombre");

                            b1.HasKey("TipoGastoId");

                            b1.ToTable("TiposGasto");

                            b1.WithOwner()
                                .HasForeignKey("TipoGastoId");
                        });

                    b.Navigation("Descripcion")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.HasOne("Libreria.LogicaNegocio.Entidades.Equipo", "Equipo")
                        .WithMany("Usuarios")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoApellido", "Apellido", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Apellido");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoEmail", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoNombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nombre");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoPassword", "Password", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Password");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Apellido")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.PagoRecurrente", b =>
                {
                    b.OwnsOne("Libreria.LogicaNegocio.Vo.VoPeriodoPago", "Periodo", b1 =>
                        {
                            b1.Property<int>("PagoRecurrenteId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("FechaDesde")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaDesde");

                            b1.Property<DateTime?>("FechaHasta")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaHasta");

                            b1.HasKey("PagoRecurrenteId");

                            b1.ToTable("Pagos");

                            b1.WithOwner()
                                .HasForeignKey("PagoRecurrenteId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
